#!/bin/bash
set -e

vms=$(ls -d /vmtank/*)
props=$(vm-list-props)

for vm in $vms; do
  name=$(basename $vm)
  echo $name:

  for prop in $props; do
    echo "  $prop: $(vm-get-prop $prop $name)"
  done
done

