#!/usr/bin/python

import qmp
import sys

vm = sys.argv[1]
qmp_path = '/vmtank/' + str(vm) + '/qmp'

monitor = qmp.QEMUMonitorProtocol(qmp_path)
monitor.connect()
monitor.cmd('system_powerdown')
monitor.close()

sys.exit(0)
